### PR TITLE
Generalize CUDNN pooling.

### PR DESCRIPTION
**Pull request by lucasb-eyer**
I will hold off merging this for a few days, as it breaks API! (ping @elPistolero)

I'm doing this to support average-pooling, and creating a second class for that would duplicate a lot of code. Since we broke that exact API just recently, ... I'll keep breaking it :)

But this also adds an assertion guarding against the previous API. I will remove that protection in the mid-future when I'll add 1D pooling.

### CODE REVIEW

**Comment by isaak-l** [comment]
Nice. I was also thinking about that.

**Comment by isaak-l** [comment]
Should we merge this now?

**Comment by lucasb-eyer** [comment]
Yes, sorry, got a sudden mountain of work :-/

**Comment by lucasb-eyer** [comment]
Also forgot to ping @yobibyte

**Pull request merged**
