### PR TITLE
[WIP] 3D convnet

### PR DESCRIPTION
**Pull request by isaak-l**
I tested this version and it seems to be working with a similar setup to the MNIST example.
Let me know what you think.

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
Only took a cursory look so far, I might not have time to comment before Monday. Would you mind trying to [rebasing](http://www-cs-students.stanford.edu/~blynn/gitmagic/ch05.html) and force-pushing to clean up history somewhat?

**Comment by isaak-l** [comment]
I'll get to it on Monday.

**Comment by isaak-l** [comment]
I rebased to clean up the history as requested.

**Comment by isaak-l** [comment]
Closed for #22

**Pull request closed without merging**
